learning_auth0/basic_app/urls.py
from django.urls import path
from basic_app import views

#template taggin
app_name = 'basic_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login')
]

learning_auth0/learning_auth0/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),#Home
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

learning_auth0/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=True)

    # Additional stuff

    portfolio_site=models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_auth0/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_auth0/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm,UserForm

#imports for login
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("You're logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered=True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                            {'user_form': user_form,
                             'profile_form':profile_form,
                             'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Not active')
        else:
            print("Someone tried to login and fail!")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid information!")

    else:
        return render(request,'basic_app/login.html',{})

learning_auth0/templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <div class="container">
        <ul class="navbar-nav">
          <li class="nav-item"> <a class="navbar-brand" href="{%url 'index'%}">Home</a> </li>
          <li class="nav-item"> <a class="nav-link"href="{% url 'admin:index' %}">Admin</a> </li>
          <li class="nav-item"> <a class="nav-link"href="{% url 'basic_app:register'%}">Register</a> </li>

          {% if user.is_authenticated %}
          <li class="nav-item"> <a class="nav-link"href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
          <li class="nav-item"> <a class="nav-link"href="{% url 'basic_app:user_login' %}">Login</a> </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock%}
    </div>

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

learning_auth0/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>This is the Home</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

learning_auth0/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class="jumbotron">

  <h1>Please Login</h1>
  <form class="" action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter your Username">

    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter your Password">

    <input type="submit" name="" value="Login">
  </form>

</div>


{% endblock %}

learning_auth0/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="register">
  </form>
  {% endif %}
</div>

{% endblock %}